SmartShudao:
  # 认证、鉴权
  auth: {
    token_jwt_secret_key: "shudaodao_1234567890_shudaodao_0987654321_shudaodao"
  }
  # 存储
  storage:
    # 数据库
    database:
      # 数据库 Auth   默认定义在 base.yaml
      # 数据库 Admin  默认定义在 base.yaml
      # 数据库 Enum   默认定义在 base.yaml
      - { name: "Shudaodao_Admin",  enabled: true,  dialect: "sqlite", driver: "aiosqlite",
          url: "database/shudaodao_admin.db",
          connect_args: { "check_same_thread": False },  echo: false
      }
      - { name: "Generate",  enabled: true,
          dialect: "postgresql", driver: "asyncpg",
          url: "postgres:postgres@localhost:5432/postgres",
          connect_args: { },
          echo: false
      }
