SmartShudao:
  # 正确做法
  # 用环境变量 代替 各种密钥和密码
  # 如:  token_jwt_secret_key: "${JWT_SECRET_KEY}"

  # 存储
  storage:
    # 数据库
    database:
      # 数据库 Auth   默认定义在 base.yaml
      # 数据库 Admin  默认定义在 base.yaml
      # 数据库 Enum   默认定义在 base.yaml

#      - { name: "Core",  enabled: true,
#          dialect: "sqlite", driver: "aiosqlite",
#          url: "database/auth_user.db",
#          connect_args: { "check_same_thread": False },
#          echo: false
#      }
      - { name: "Common",  enabled: true,
          dialect: "sqlite", driver: "aiosqlite",
          url: "database/shudaodao_common.db",
          connect_args: { "check_same_thread": False },
          echo: false
      }

