SmartShudao:

  # 正确做法
  # 用环境变量 代替 各种密钥和密码
  # 如:  token_jwt_secret_key: "${JWT_SECRET_KEY}"



  # 存储
  storage:
    # 数据库
    database:
      - { name: "Core",  enabled: true,
          dialect: "sqlite", driver: "aiosqlite",
          url: "database/auth_user.db",
          connect_args: { "check_same_thread": False },
          echo: false
      }
      - { name: "Common",  enabled: true,
          dialect: "sqlite", driver: "aiosqlite",
          url: "database/test.db",
          connect_args: { "check_same_thread": False },
          echo: false
      }

